# Global Subs:
substitutions:
  display_name: heater
  comment: Heat Storm HS-1500-WIFI 1500W Heater

esphome:
  name: ${display_name}
  comment: ${comment}

esp8266:
  board: esp01_1m

# Make sure logging is not using the serial port for Tuya commands
logger:
  baud_rate: 0

# Enable Home Assistant API
api:
  encryption:
    key: !secret heater_key

ota:
  password: !secret password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: ${display_name}_AP
    password: !secret wifi_password
    ap_timeout: 5min

captive_portal:

# Set GPIO pins for Tuya MCU communication
uart:  
  rx_pin: GPIO3
  tx_pin: GPIO1  
  baud_rate: 9600

# Register the Tuya MCU connection and set ID for lambda calls
tuya:
  id: "tuya_heater"

# Controls
climate:
  - platform: tuya
    id: heater_climate_c
    name: "Heater Controls (C)"
    switch_datapoint: 1
    target_temperature_datapoint: 2
    current_temperature_datapoint: 3
    reports_fahrenheit: false
    visual:
      min_temperature: 4
      max_temperature: 37
      temperature_step: 1.0
  - platform: tuya
    id: heater_climate_f
    name: "Heater Controls (F)"
    switch_datapoint: 1
    target_temperature_datapoint: 20
    current_temperature_datapoint: 21
    reports_fahrenheit: true
    visual:
      min_temperature: 40
      max_temperature: 99
      temperature_step: 1.0
switch:
  - platform: "tuya"
    id: lock
    name: "Child Lock"
    icon: "mdi:account-lock-outline"
    switch_datapoint: 7
    inverted: true
    restore_mode: RESTORE_DEFAULT_OFF
    device_class: "switch"
select:
  - platform: tuya
    id: mode
    name: "Mode"
    icon: "mdi:fan-auto"
    enum_datapoint: 4
    options:
      0: "Auto"
      1: "Low"
      2: "High"
    optimistic: true
  - platform: tuya
    id: brightness
    name: "Brightness"
    icon: "mdi:brightness-percent"
    enum_datapoint: 5
    options:
      0: "Off"
      1: "10%"
      2: "50%"
      3: "100%"
    optimistic: true
  - platform: "tuya"
    id: temp_unit_convert
    name: "Temperature Units"
    icon: "mdi:temperature-celsius"
    enum_datapoint: 19
    options:
      0: "°C"
      1: "°F"

# Sensors
binary_sensor:
  - platform: "tuya"
    id: fault
    name: "Fault Alarm"
    sensor_datapoint: 13
    icon: "mdi:alert-outline"
    device_class: "problem"
